spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:markcollab}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}


jwt.secret=${JWT_SECRET:q82vJk5W3zTrL9mPfYDgaX6RCuNEsM7vhKbU2dFe1QpB0Axl}

email.api.url=${EMAIL_API_URL:http://localhost:8000/api/email/enviar-contato}
